- name: add postgresql repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  sudo: yes

- name: add postgresql repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
  sudo: yes

- name: install build depends
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - python-pycurl
    - python-psycopg2
    - libpq-dev
    - "postgresql-{{ postgresql_version }}"

- name: restart postgresql
  service: name=postgresql state=started
  sudo: yes

- name: create postgresql user
  postgresql_user:
    name: "{{ deploy }}"
    password: "{{ password }}"
    port: "{{ postgresql_port }}"
    state: present
    login_user: postgres
  sudo: yes
  sudo_user: postgres
