- name: install build depends
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libffi-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev

- name: clone rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git dest=~{{ deploy }}/.rbenv version=v0.4.0 accept_hostkey=yes

- name: create ~/.bash.d/ (if not exists)
  file: dest=~{{ deploy }}/.bash.d/ state=directory

- name: copy 50_rbenv.bash to ~/.bash.d/
  copy: src=50_rbenv.bash dest=~{{ deploy }}/.bash.d/50_rbenv.bash mode=700 owner={{ deploy }}

- name: add rbenv to ~/.bash_profile
  lineinfile: dest=~{{ deploy }}/.bash_profile regexp="rbenv" insertafter=EOF line="source ~/.bash.d/50_rbenv.bash" create=yes owner={{deploy}}

- name: create ~/.rbenv/plugins/ (if not exists)
  file: path=~{{ deploy }}/.rbenv/plugins/ owner={{ deploy }} group={{ deploy }} mode=0755 state=directory

- name: clone ruby-build repo
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~{{ deploy }}/.rbenv/plugins/ruby-build
