- name: check if target ruby is installed
  shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
  changed_when: false
  ignore_errors: yes
  register: ruby_installed

- name: rbenv install {{ ruby_version }}
  shell: bash -lc "MAKE_OPTS='-j 4' rbenv install {{ ruby_version }}"
  when: ruby_installed|failed

- name: set global ruby_version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: ruby_installed|failed

- name: install bundler
  shell: bash -lc "gem install bundler"
